apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name | quote }}
  namespace: kube-system
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  ciliumnetworkpolicies.yaml: |-
    {{- .Files.Get "files/crds/ciliumnetworkpolicies.yaml" | nindent 4 }}
  ciliumclusterwidenetworkpolicies.yaml: |-
    {{- .Files.Get "files/crds/ciliumclusterwidenetworkpolicies.yaml" | nindent 4 }}