version: 2.1
orbs:
  architect: giantswarm/architect@4.28.1

workflows:
  version: 2
  build:
    jobs:
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-default-app-catalog
        app_catalog: default-catalog
        app_catalog_test: default-test-catalog
        chart: cilium-prerequisites
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        name: push-to-giantswarm-app-catalog
        context: architect
        executor: app-build-suite
        app_catalog: giantswarm-catalog
        app_catalog_test: giantswarm-test-catalog
        chart: cilium-prerequisites
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/

          branches:
            ignore:
            - main
            - master
